'use client';

import { useState } from 'react';

const ISSUE_TYPES = [
  { zh: '破损',   ja: '破損',      en: 'Cargo Damage' },
  { zh: '延误',   ja: '遅延',      en: 'Flight/Delivery Delay' },
  { zh: '文件错误', ja: '書類エラー', en: 'Documentation Error' },
  { zh: '温度超标', ja: '温度超過',  en: 'Temperature Exceedance' },
  { zh: '短装',   ja: '短積',      en: 'Short Shipment' },
  { zh: '多装',   ja: '超過積載',   en: 'Over Shipment' },
  { zh: '货物丢失', ja: '貨物紛失',  en: 'Cargo Loss' },
  { zh: '其他',   ja: 'その他',     en: 'Other' },
];

interface FormData {
  awb: string;
  customer: string;
  issueType: string;
  location: string;
  discoveredAt: string;
  details: string;
}

interface Reports { zh: string; ja: string; en: string; }

const EMPTY: FormData = { awb: '', customer: '', issueType: '', location: '', discoveredAt: '', details: '' };

function inputStyle(hasError = false): React.CSSProperties {
  return {
    width: '100%',
    background: 'var(--dark2)',
    border: `1px solid ${hasError ? 'var(--red)' : 'var(--border)'}`,
    borderRadius: 8,
    padding: '10px 14px',
    color: 'var(--text)',
    fontSize: 14,
    outline: 'none',
    transition: 'border-color 0.2s',
  };
}

function generateReports(f: FormData): Reports {
  const type = ISSUE_TYPES.find((t) => t.zh === f.issueType);
  const typeJa = type?.ja ?? f.issueType;
  const typeEn = type?.en ?? f.issueType;

  return {
    zh: `【货物异常报告】
━━━━━━━━━━━━━━━━━━━━━
AWB番号　　：${f.awb}
客户名称　　：${f.customer}
异常类型　　：${f.issueType}
发生地点　　：${f.location}
发现时间　　：${f.discoveredAt}
━━━━━━━━━━━━━━━━━━━━━
【异常详情】
${f.details}
━━━━━━━━━━━━━━━━━━━━━
本报告由 OPTEC Express 品质管理部生成。`,

    ja: `【貨物異常報告】
━━━━━━━━━━━━━━━━━━━━━
AWB番号　　：${f.awb}
お客様名　　：${f.customer}
異常種別　　：${typeJa}
発生場所　　：${f.location}
発見日時　　：${f.discoveredAt}
━━━━━━━━━━━━━━━━━━━━━
【異常詳細】
${f.details}
━━━━━━━━━━━━━━━━━━━━━
本報告は OPTEC Express 品質管理部が作成しました。`,

    en: `[CARGO IRREGULARITY REPORT]
━━━━━━━━━━━━━━━━━━━━━
AWB No.       : ${f.awb}
Customer      : ${f.customer}
Issue Type    : ${typeEn}
Location      : ${f.location}
Discovered At : ${f.discoveredAt}
━━━━━━━━━━━━━━━━━━━━━
[Details]
${f.details}
━━━━━━━━━━━━━━━━━━━━━
This report was generated by OPTEC Express Quality Management Dept.`,
  };
}

export default function Home() {
  const [form, setForm] = useState<FormData>(EMPTY);
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, boolean>>>({});
  const [reports, setReports] = useState<Reports | null>(null);
  const [copied, setCopied] = useState<'zh' | 'ja' | 'en' | null>(null);

  function set(field: keyof FormData, value: string) {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) setErrors((prev) => ({ ...prev, [field]: false }));
  }

  function validate(): boolean {
    const required: (keyof FormData)[] = ['awb', 'customer', 'issueType', 'location', 'discoveredAt', 'details'];
    const newErrors: Partial<Record<keyof FormData, boolean>> = {};
    for (const f of required) {
      if (!form[f].trim()) newErrors[f] = true;
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  function handleGenerate() {
    if (!validate()) return;
    setReports(generateReports(form));
    setCopied(null);
  }

  function handleCopy(lang: 'zh' | 'ja' | 'en') {
    if (!reports) return;
    navigator.clipboard.writeText(reports[lang]).then(() => {
      setCopied(lang);
      setTimeout(() => setCopied(null), 2500);
    });
  }

  function handleReset() {
    setForm(EMPTY);
    setErrors({});
    setReports(null);
    setCopied(null);
  }

  const LANG_LABELS: { key: 'zh' | 'ja' | 'en'; label: string }[] = [
    { key: 'zh', label: '中文版' },
    { key: 'ja', label: '日本語版' },
    { key: 'en', label: 'English' },
  ];

  return (
    <div style={{ minHeight: '100vh', background: 'var(--dark)' }}>
      {/* Header */}
      <header style={{ background: 'var(--dark2)', borderBottom: '1px solid var(--border)', padding: '24px 32px' }}>
        <div style={{ maxWidth: 960, margin: '0 auto' }}>
          <div style={{ fontSize: 12, color: 'var(--gold)', letterSpacing: 3, marginBottom: 8 }}>
            OPTEC EXPRESS · QUALITY MANAGEMENT
          </div>
          <h1 style={{ fontSize: 28, color: 'var(--gold)', fontFamily: 'Georgia, serif', marginBottom: 4 }}>
            货物异常快速报告生成器
          </h1>
          <p style={{ fontSize: 13, color: 'var(--text-dim)' }}>
            填表 → 自动生成中 / 日 / 英三语报告文本
          </p>
        </div>
      </header>

      <main style={{ maxWidth: 960, margin: '0 auto', padding: '32px 24px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: reports ? '1fr 1fr' : '1fr', gap: 24 }}>

          {/* Form */}
          <div style={{ background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 14, padding: '28px' }}>
            <h2 style={{ fontSize: 15, color: 'var(--gold)', marginBottom: 22, fontFamily: 'Georgia, serif' }}>
              填写异常信息
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>

              {/* AWB + Customer */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
                {[
                  { key: 'awb' as const,      label: 'AWB 号',   placeholder: '例：160-12345678' },
                  { key: 'customer' as const,  label: '客户名称', placeholder: '例：ABC Electronics Co.' },
                ].map(({ key, label, placeholder }) => (
                  <div key={key}>
                    <label style={{ display: 'block', fontSize: 13, color: 'var(--gold)', marginBottom: 6 }}>
                      {label} <span style={{ color: 'var(--red)' }}>*</span>
                    </label>
                    <input type="text" placeholder={placeholder} value={form[key]}
                      onChange={(e) => set(key, e.target.value)} style={inputStyle(!!errors[key])} />
                    {errors[key] && <p style={{ fontSize: 11, color: 'var(--red)', marginTop: 4 }}>必填项</p>}
                  </div>
                ))}
              </div>

              {/* Issue Type */}
              <div>
                <label style={{ display: 'block', fontSize: 13, color: 'var(--gold)', marginBottom: 6 }}>
                  异常类型 <span style={{ color: 'var(--red)' }}>*</span>
                </label>
                <select value={form.issueType} onChange={(e) => set('issueType', e.target.value)}
                  style={{ ...inputStyle(!!errors.issueType), cursor: 'pointer' }}>
                  <option value="">请选择异常类型</option>
                  {ISSUE_TYPES.map((t) => <option key={t.zh} value={t.zh}>{t.zh}</option>)}
                </select>
                {errors.issueType && <p style={{ fontSize: 11, color: 'var(--red)', marginTop: 4 }}>必填项</p>}
              </div>

              {/* Location + Time */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 13, color: 'var(--gold)', marginBottom: 6 }}>
                    发生地点 <span style={{ color: 'var(--red)' }}>*</span>
                  </label>
                  <input type="text" placeholder="例：上海浦东国际机场（PVG）货站"
                    value={form.location} onChange={(e) => set('location', e.target.value)}
                    style={inputStyle(!!errors.location)} />
                  {errors.location && <p style={{ fontSize: 11, color: 'var(--red)', marginTop: 4 }}>必填项</p>}
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 13, color: 'var(--gold)', marginBottom: 6 }}>
                    发现时间 <span style={{ color: 'var(--red)' }}>*</span>
                  </label>
                  <input type="datetime-local" value={form.discoveredAt}
                    onChange={(e) => set('discoveredAt', e.target.value)}
                    style={{ ...inputStyle(!!errors.discoveredAt), colorScheme: 'dark' }} />
                  {errors.discoveredAt && <p style={{ fontSize: 11, color: 'var(--red)', marginTop: 4 }}>必填项</p>}
                </div>
              </div>

              {/* Details */}
              <div>
                <label style={{ display: 'block', fontSize: 13, color: 'var(--gold)', marginBottom: 6 }}>
                  详细说明 <span style={{ color: 'var(--red)' }}>*</span>
                </label>
                <textarea rows={5} placeholder="请详细描述异常情况，包括：货物状态、数量影响、初步原因分析等..."
                  value={form.details} onChange={(e) => set('details', e.target.value)}
                  style={{ ...inputStyle(!!errors.details), resize: 'vertical', lineHeight: 1.7 }} />
                {errors.details && <p style={{ fontSize: 11, color: 'var(--red)', marginTop: 4 }}>必填项</p>}
              </div>

              {/* Buttons */}
              <div style={{ display: 'flex', gap: 10 }}>
                <button onClick={handleGenerate} style={{
                  flex: 1, padding: '13px', borderRadius: 10, border: 'none',
                  background: 'linear-gradient(90deg, var(--gold), #e8c99a)',
                  color: 'var(--dark)', fontFamily: 'Georgia, serif',
                  fontSize: 15, fontWeight: 700, cursor: 'pointer', letterSpacing: 0.5,
                }}>
                  生成报告
                </button>
                {reports && (
                  <button onClick={handleReset} style={{
                    padding: '13px 20px', borderRadius: 10,
                    border: '1px solid var(--border)', background: 'transparent',
                    color: 'var(--text-dim)', fontFamily: 'Georgia, serif',
                    fontSize: 14, cursor: 'pointer',
                  }}>
                    重置
                  </button>
                )}
              </div>
            </div>
          </div>

          {/* Report Output — three sections */}
          {reports && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {LANG_LABELS.map(({ key, label }) => (
                <div key={key} style={{
                  background: 'var(--card)',
                  border: '1px solid rgba(76,175,80,0.35)',
                  borderRadius: 12, padding: '18px 20px',
                  display: 'flex', flexDirection: 'column', gap: 10,
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span style={{ fontSize: 13, color: 'var(--gold)', fontFamily: 'Georgia, serif', fontWeight: 600 }}>
                      {label}
                    </span>
                    <button onClick={() => handleCopy(key)} style={{
                      padding: '5px 16px', borderRadius: 6,
                      border: `1px solid ${copied === key ? 'rgba(76,175,80,0.6)' : 'var(--border)'}`,
                      background: copied === key ? 'rgba(76,175,80,0.15)' : 'transparent',
                      color: copied === key ? 'var(--green)' : 'var(--gold)',
                      fontFamily: 'Georgia, serif', fontSize: 12,
                      cursor: 'pointer', transition: 'all 0.2s',
                      fontWeight: copied === key ? 700 : 400,
                    }}>
                      {copied === key ? '✓ 已复制' : '复制'}
                    </button>
                  </div>
                  <textarea readOnly value={reports[key]} style={{
                    background: 'var(--dark2)',
                    border: '1px solid var(--border)',
                    borderRadius: 6, padding: '10px 12px',
                    color: 'var(--text)', fontSize: 11,
                    lineHeight: 1.8, resize: 'none',
                    fontFamily: 'monospace', outline: 'none',
                    height: 180,
                  }} />
                </div>
              ))}
            </div>
          )}
        </div>
      </main>

      <footer style={{ textAlign: 'center', padding: '24px', borderTop: '1px solid var(--border)', color: 'var(--text-dim)', fontSize: 12, marginTop: 20 }}>
        OPTEC Express · Cargo Irregularity Report Generator · {new Date().getFullYear()}
      </footer>
    </div>
  );
}
