export const COUNTRY_NAMES: Record<string, { zh: string; ja: string; en: string }> = {
  JP: { zh: '日本', ja: '日本', en: 'Japan' },
  CN: { zh: '中国', ja: '中国', en: 'China' },
  KR: { zh: '韩国', ja: '韓国', en: 'South Korea' },
  TW: { zh: '台湾', ja: '台湾', en: 'Taiwan' },
  HK: { zh: '香港', ja: '香港', en: 'Hong Kong' },
  MO: { zh: '澳门', ja: 'マカオ', en: 'Macau' },
  SG: { zh: '新加坡', ja: 'シンガポール', en: 'Singapore' },
  MY: { zh: '马来西亚', ja: 'マレーシア', en: 'Malaysia' },
  TH: { zh: '泰国', ja: 'タイ', en: 'Thailand' },
  ID: { zh: '印度尼西亚', ja: 'インドネシア', en: 'Indonesia' },
  PH: { zh: '菲律宾', ja: 'フィリピン', en: 'Philippines' },
  VN: { zh: '越南', ja: 'ベトナム', en: 'Vietnam' },
  MM: { zh: '缅甸', ja: 'ミャンマー', en: 'Myanmar' },
  KH: { zh: '柬埔寨', ja: 'カンボジア', en: 'Cambodia' },
  LA: { zh: '老挝', ja: 'ラオス', en: 'Laos' },
  IN: { zh: '印度', ja: 'インド', en: 'India' },
  LK: { zh: '斯里兰卡', ja: 'スリランカ', en: 'Sri Lanka' },
  BD: { zh: '孟加拉国', ja: 'バングラデシュ', en: 'Bangladesh' },
  NP: { zh: '尼泊尔', ja: 'ネパール', en: 'Nepal' },
  PK: { zh: '巴基斯坦', ja: 'パキスタン', en: 'Pakistan' },
  AE: { zh: '阿联酋', ja: 'アラブ首長国連邦', en: 'UAE' },
  QA: { zh: '卡塔尔', ja: 'カタール', en: 'Qatar' },
  BH: { zh: '巴林', ja: 'バーレーン', en: 'Bahrain' },
  KW: { zh: '科威特', ja: 'クウェート', en: 'Kuwait' },
  OM: { zh: '阿曼', ja: 'オマーン', en: 'Oman' },
  SA: { zh: '沙特阿拉伯', ja: 'サウジアラビア', en: 'Saudi Arabia' },
  JO: { zh: '约旦', ja: 'ヨルダン', en: 'Jordan' },
  LB: { zh: '黎巴嫩', ja: 'レバノン', en: 'Lebanon' },
  IL: { zh: '以色列', ja: 'イスラエル', en: 'Israel' },
  IQ: { zh: '伊拉克', ja: 'イラク', en: 'Iraq' },
  IR: { zh: '伊朗', ja: 'イラン', en: 'Iran' },
  TR: { zh: '土耳其', ja: 'トルコ', en: 'Turkey' },
  SY: { zh: '叙利亚', ja: 'シリア', en: 'Syria' },
  AF: { zh: '阿富汗', ja: 'アフガニスタン', en: 'Afghanistan' },
  GB: { zh: '英国', ja: 'イギリス', en: 'United Kingdom' },
  FR: { zh: '法国', ja: 'フランス', en: 'France' },
  DE: { zh: '德国', ja: 'ドイツ', en: 'Germany' },
  NL: { zh: '荷兰', ja: 'オランダ', en: 'Netherlands' },
  BE: { zh: '比利时', ja: 'ベルギー', en: 'Belgium' },
  CH: { zh: '瑞士', ja: 'スイス', en: 'Switzerland' },
  AT: { zh: '奥地利', ja: 'オーストリア', en: 'Austria' },
  CZ: { zh: '捷克', ja: 'チェコ', en: 'Czech Republic' },
  HU: { zh: '匈牙利', ja: 'ハンガリー', en: 'Hungary' },
  PL: { zh: '波兰', ja: 'ポーランド', en: 'Poland' },
  NO: { zh: '挪威', ja: 'ノルウェー', en: 'Norway' },
  SE: { zh: '瑞典', ja: 'スウェーデン', en: 'Sweden' },
  DK: { zh: '丹麦', ja: 'デンマーク', en: 'Denmark' },
  FI: { zh: '芬兰', ja: 'フィンランド', en: 'Finland' },
  IT: { zh: '意大利', ja: 'イタリア', en: 'Italy' },
  ES: { zh: '西班牙', ja: 'スペイン', en: 'Spain' },
  PT: { zh: '葡萄牙', ja: 'ポルトガル', en: 'Portugal' },
  RU: { zh: '俄罗斯', ja: 'ロシア', en: 'Russia' },
  UA: { zh: '乌克兰', ja: 'ウクライナ', en: 'Ukraine' },
  AZ: { zh: '阿塞拜疆', ja: 'アゼルバイジャン', en: 'Azerbaijan' },
  GE: { zh: '格鲁吉亚', ja: 'ジョージア', en: 'Georgia' },
  AM: { zh: '亚美尼亚', ja: 'アルメニア', en: 'Armenia' },
  KZ: { zh: '哈萨克斯坦', ja: 'カザフスタン', en: 'Kazakhstan' },
  UZ: { zh: '乌兹别克斯坦', ja: 'ウズベキスタン', en: 'Uzbekistan' },
  TM: { zh: '土库曼斯坦', ja: 'トルクメニスタン', en: 'Turkmenistan' },
  TJ: { zh: '塔吉克斯坦', ja: 'タジキスタン', en: 'Tajikistan' },
  KG: { zh: '吉尔吉斯斯坦', ja: 'キルギスタン', en: 'Kyrgyzstan' },
  MN: { zh: '蒙古国', ja: 'モンゴル', en: 'Mongolia' },
  GR: { zh: '希腊', ja: 'ギリシャ', en: 'Greece' },
  RO: { zh: '罗马尼亚', ja: 'ルーマニア', en: 'Romania' },
  BG: { zh: '保加利亚', ja: 'ブルガリア', en: 'Bulgaria' },
  HR: { zh: '克罗地亚', ja: 'クロアチア', en: 'Croatia' },
  RS: { zh: '塞尔维亚', ja: 'セルビア', en: 'Serbia' },
  SI: { zh: '斯洛文尼亚', ja: 'スロベニア', en: 'Slovenia' },
  MK: { zh: '北马其顿', ja: '北マケドニア', en: 'North Macedonia' },
  AL: { zh: '阿尔巴尼亚', ja: 'アルバニア', en: 'Albania' },
  LV: { zh: '拉脱维亚', ja: 'ラトビア', en: 'Latvia' },
  EE: { zh: '爱沙尼亚', ja: 'エストニア', en: 'Estonia' },
  LT: { zh: '立陶宛', ja: 'リトアニア', en: 'Lithuania' },
  LU: { zh: '卢森堡', ja: 'ルクセンブルク', en: 'Luxembourg' },
  IE: { zh: '爱尔兰', ja: 'アイルランド', en: 'Ireland' },
  IS: { zh: '冰岛', ja: 'アイスランド', en: 'Iceland' },
  AU: { zh: '澳大利亚', ja: 'オーストラリア', en: 'Australia' },
  NZ: { zh: '新西兰', ja: 'ニュージーランド', en: 'New Zealand' },
  GU: { zh: '关岛', ja: 'グアム', en: 'Guam' },
  PF: { zh: '法属波利尼西亚', ja: 'フランス領ポリネシア', en: 'French Polynesia' },
  FJ: { zh: '斐济', ja: 'フィジー', en: 'Fiji' },
  SB: { zh: '所罗门群岛', ja: 'ソロモン諸島', en: 'Solomon Islands' },
  US: { zh: '美国', ja: 'アメリカ', en: 'United States' },
  CA: { zh: '加拿大', ja: 'カナダ', en: 'Canada' },
  MX: { zh: '墨西哥', ja: 'メキシコ', en: 'Mexico' },
  GT: { zh: '危地马拉', ja: 'グアテマラ', en: 'Guatemala' },
  HN: { zh: '洪都拉斯', ja: 'ホンジュラス', en: 'Honduras' },
  NI: { zh: '尼加拉瓜', ja: 'ニカラグア', en: 'Nicaragua' },
  CR: { zh: '哥斯达黎加', ja: 'コスタリカ', en: 'Costa Rica' },
  PA: { zh: '巴拿马', ja: 'パナマ', en: 'Panama' },
  SV: { zh: '萨尔瓦多', ja: 'エルサルバドル', en: 'El Salvador' },
  CU: { zh: '古巴', ja: 'キューバ', en: 'Cuba' },
  JM: { zh: '牙买加', ja: 'ジャマイカ', en: 'Jamaica' },
  BS: { zh: '巴哈马', ja: 'バハマ', en: 'Bahamas' },
  HT: { zh: '海地', ja: 'ハイチ', en: 'Haiti' },
  DO: { zh: '多米尼加共和国', ja: 'ドミニカ共和国', en: 'Dominican Republic' },
  PR: { zh: '波多黎各', ja: 'プエルトリコ', en: 'Puerto Rico' },
  TT: { zh: '特立尼达和多巴哥', ja: 'トリニダード・トバゴ', en: 'Trinidad and Tobago' },
  BR: { zh: '巴西', ja: 'ブラジル', en: 'Brazil' },
  AR: { zh: '阿根廷', ja: 'アルゼンチン', en: 'Argentina' },
  CL: { zh: '智利', ja: 'チリ', en: 'Chile' },
  CO: { zh: '哥伦比亚', ja: 'コロンビア', en: 'Colombia' },
  PE: { zh: '秘鲁', ja: 'ペルー', en: 'Peru' },
  EC: { zh: '厄瓜多尔', ja: 'エクアドル', en: 'Ecuador' },
  VE: { zh: '委内瑞拉', ja: 'ベネズエラ', en: 'Venezuela' },
  BO: { zh: '玻利维亚', ja: 'ボリビア', en: 'Bolivia' },
  PY: { zh: '巴拉圭', ja: 'パラグアイ', en: 'Paraguay' },
  UY: { zh: '乌拉圭', ja: 'ウルグアイ', en: 'Uruguay' },
  GY: { zh: '圭亚那', ja: 'ガイアナ', en: 'Guyana' },
  SR: { zh: '苏里南', ja: 'スリナム', en: 'Suriname' },
  GF: { zh: '法属圭亚那', ja: 'フランス領ギアナ', en: 'French Guiana' },
  ZA: { zh: '南非', ja: '南アフリカ', en: 'South Africa' },
  EG: { zh: '埃及', ja: 'エジプト', en: 'Egypt' },
  ET: { zh: '埃塞俄比亚', ja: 'エチオピア', en: 'Ethiopia' },
  KE: { zh: '肯尼亚', ja: 'ケニア', en: 'Kenya' },
  TZ: { zh: '坦桑尼亚', ja: 'タンザニア', en: 'Tanzania' },
  UG: { zh: '乌干达', ja: 'ウガンダ', en: 'Uganda' },
  NG: { zh: '尼日利亚', ja: 'ナイジェリア', en: 'Nigeria' },
  GH: { zh: '加纳', ja: 'ガーナ', en: 'Ghana' },
  CI: { zh: '科特迪瓦', ja: 'コートジボワール', en: "Cote d'Ivoire" },
  SN: { zh: '塞内加尔', ja: 'セネガル', en: 'Senegal' },
  MA: { zh: '摩洛哥', ja: 'モロッコ', en: 'Morocco' },
  TN: { zh: '突尼斯', ja: 'チュニジア', en: 'Tunisia' },
  DZ: { zh: '阿尔及利亚', ja: 'アルジェリア', en: 'Algeria' },
  LY: { zh: '利比亚', ja: 'リビア', en: 'Libya' },
  SD: { zh: '苏丹', ja: 'スーダン', en: 'Sudan' },
  DJ: { zh: '吉布提', ja: 'ジブチ', en: 'Djibouti' },
  SO: { zh: '索马里', ja: 'ソマリア', en: 'Somalia' },
  ER: { zh: '厄立特里亚', ja: 'エリトリア', en: 'Eritrea' },
  RW: { zh: '卢旺达', ja: 'ルワンダ', en: 'Rwanda' },
  TG: { zh: '多哥', ja: 'トーゴ', en: 'Togo' },
  GN: { zh: '几内亚', ja: 'ギニア', en: 'Guinea' },
  SL: { zh: '塞拉利昂', ja: 'シエラレオネ', en: 'Sierra Leone' },
  LR: { zh: '利比里亚', ja: 'リベリア', en: 'Liberia' },
}
